# Generated by Django 4.2.8 on 2024-08-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagePrincipal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
