# Generated by Django 4.2.8 on 2024-05-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagePrincipal', '0002_room_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='remaining_spaces',
            field=models.IntegerField(default=0),
        ),
    ]
