# Generated by Django 4.2.8 on 2024-08-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagePrincipal', '0002_alter_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
        migrations.AddField(
            model_name='room',
            name='person1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
