# Generated by Django 4.2.8 on 2024-05-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagePrincipal', '0003_room_remaining_spaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='remaining_spaces',
            field=models.IntegerField(default=4),
        ),
    ]
