# Generated by Django 4.2.8 on 2024-08-29 01:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pageLogin', '0009_remove_companions_bus_remove_companions_person1_and_more'),
        ('pagePrincipal', '0005_remove_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.RemoveField(
            model_name='room',
            name='person1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='person2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='person3',
        ),
        migrations.RemoveField(
            model_name='room',
            name='person4',
        ),
        migrations.AddField(
            model_name='room',
            name='companions',
            field=models.ManyToManyField(blank=True, to='pageLogin.companions'),
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
