# Generated by Django 4.2.8 on 2024-08-29 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pageLogin', '0009_remove_companions_bus_remove_companions_person1_and_more'),
        ('pagePrincipal', '0006_alter_room_options_remove_room_person1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='companions',
            field=models.ManyToManyField(blank=True, null=True, to='pageLogin.companions'),
        ),
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
