# Generated by Django 4.2.8 on 2024-07-30 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='DatesOfTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateField()),
                ('second_date', models.DateField()),
            ],
            options={
                'verbose_name': 'DateOfTravel',
                'verbose_name_plural': 'DatesOfTravels',
            },
        ),
        migrations.CreateModel(
            name='UserMoreInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.IntegerField()),
                ('price', models.FloatField()),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pageLogin.bus')),
                ('date_of_travel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pageLogin.datesoftravel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserMoreInformation',
                'verbose_name_plural': 'UserMoreInformations',
            },
        ),
        migrations.CreateModel(
            name='Rooms_Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pageLogin.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Companions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person1', models.CharField(blank=True, max_length=100, null=True)),
                ('person2', models.CharField(blank=True, max_length=100, null=True)),
                ('person3', models.CharField(blank=True, max_length=100, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pageLogin.bus')),
                ('room_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pageLogin.rooms_bus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Companion',
                'verbose_name_plural': 'Companions',
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='date_of_travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pageLogin.datesoftravel'),
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado')], default='disponible', max_length=100)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pageLogin.bus')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
                'unique_together': {('bus', 'numero')},
            },
        ),
    ]
