# Generated by Django 4.2.8 on 2024-08-10 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pageLogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companions',
            name='room_bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pageLogin.rooms_bus'),
        ),
    ]
