# Generated by Django 4.2.8 on 2024-05-29 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pageLogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatesOfTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateField()),
                ('second_date', models.DateField()),
            ],
            options={
                'verbose_name': 'DateOfTravel',
                'verbose_name_plural': 'DatesOfTravels',
            },
        ),
        migrations.AddField(
            model_name='usermoreinformation',
            name='date_of_travel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pageLogin.datesoftravel'),
        ),
    ]
