# Generated by Django 4.2.8 on 2024-08-10 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pageLogin', '0002_alter_companions_room_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='companion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pageLogin.companions'),
        ),
    ]
