# Generated by Django 4.2.8 on 2024-05-30 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pageLogin', '0002_datesoftravel_usermoreinformation_date_of_travel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person1', models.CharField(blank=True, max_length=100, null=True)),
                ('person2', models.CharField(blank=True, max_length=100, null=True)),
                ('person3', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Companion',
                'verbose_name_plural': 'Companions',
            },
        ),
    ]
