# Generated by Django 4.2.8 on 2024-06-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageLogin', '0003_companions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoreinformation',
            name='rooms',
            field=models.CharField(max_length=10),
        ),
    ]
