# Generated by Django 4.2.8 on 2024-08-25 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pageLogin', '0004_asiento_companion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companions',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pageLogin.bus'),
        ),
    ]
