# Generated by Django 4.2.8 on 2024-08-25 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pageLogin', '0005_alter_companions_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms_bus',
            name='bus_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Secondary_Bus', to='pageLogin.bus'),
        ),
        migrations.AlterField(
            model_name='rooms_bus',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Primary_Bus', to='pageLogin.bus'),
        ),
    ]
