# Generated by Django 4.2.8 on 2024-08-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageLogin', '0006_rooms_bus_bus_2_alter_rooms_bus_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoreinformation',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
