# Generated by Django 4.2.8 on 2024-08-27 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pageLogin', '0007_usermoreinformation_vip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms_bus',
            name='bus_2',
        ),
        migrations.AlterField(
            model_name='rooms_bus',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pageLogin.bus'),
        ),
    ]
