# Generated by Django 4.2.8 on 2024-08-29 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pageLogin', '0008_remove_rooms_bus_bus_2_alter_rooms_bus_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companions',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='companions',
            name='person1',
        ),
        migrations.RemoveField(
            model_name='companions',
            name='person2',
        ),
        migrations.RemoveField(
            model_name='companions',
            name='person3',
        ),
        migrations.RemoveField(
            model_name='companions',
            name='room_bus',
        ),
        migrations.AddField(
            model_name='companions',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companions', to=settings.AUTH_USER_MODEL),
        ),
    ]
