# Generated by Django 4.2.8 on 2024-08-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_Voucher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvoucher',
            name='voucher',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
